### PR TITLE
Scenario 9 estimates from NotreDame-FRED team

### PR DESCRIPTION
**Pull request by confunguido**
## Description

Please include a brief description of your change.  

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: Notre Dame
- Model Name: NotreDame-FRED
- Institution:  University of Notre Dame
---

## Checklist

- [x] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @confunguido,

Thank you for your pull-request, I have some questions about it.

It seems that the target_end_date values in your projections are on a Friday. For "# wk" targets, the target_end_date should be the Saturday at the end of the week time period. You can find more information on this page: https://github.com/midas-network/covid19-scenario-modeling-hub/tree/master/data-processed#target_end_date. As the start date for scenarios is September 12 (first date of simulated transmission/outcomes), the 1 week target should one the 18st of September. Would it be possible to verify and update it, please?

Also, it seems that the projections you submitted are for the cumulative and incident deaths and cases for multiple states but not at US level, am I correct or did I misread the file? If so, could I ask if you are also planning to submit projections at national level and/or other targets?

Thanks and please don't hesitate to let me know if you have any questions or if I can be of further assistance.

Best,
Lucie

**Comment by confunguido** [comment]
Hi Lucie,

Thank you for your comments. I fixed the issue with the # wk targets. I hope this version is correct. We were unable to generate hospitalizations for this round, and we were unable to run DC and SD, so we can't provide National level estimates. We were planning on generating the outputs for <12 and 12+, but unfortunately ran into some issues with the university cluster and were unable to get those runs. All the other states and targets are included. 

Best regards,
Guido

**Comment by LucieContamin** [comment]
Hi Guido,

Thank you very much for the additional information and for the update. 
I notice a small typo in the target names column ("cases" instead of "case"). Would it be possible to either update it or I will be happy to fix it when I merge the file if that's ok for you?

Many thanks,
Lucie

**Comment by confunguido** [comment]
Hi Lucie, I think I fixed that typo.

**Comment by LucieContamin** [comment]
Hi Guido, 
It looks all good! Thank you very much,
Lucie

**Pull request merged**
