### PR TITLE
NCSU-COVSIM Abstract Round 13

### PR DESCRIPTION
**Pull request by erosenstrom**
## Description

uploading abstract for round 13
---

## Checklist

- [x ] Specify a proper PR title with your team name.
- [ x] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Scenario-File-Checks).

### CODE REVIEW

**Comment by LucieContamin** [comment]
HI @erosenstrom ,

Thanks for updating the Round 13 abstract. 
I just have a quick question, it looks like the section "Initial distribution of susceptibility if available" is not present in your abstract. Is that expected? Should we take this section and sub-sections as "Not available" ?

Many thanks,

Lucie

**Comment by erosenstrom** [comment]
That is correct. Should I edit the file such that it says its not available?

**Comment by LucieContamin** [comment]
That would be great, if possible. I can also do it after merging if you prefer.

Thanks,

Lucie

**Comment by erosenstrom** [comment]
I have updated the file.

**Comment by LucieContamin** [comment]
Thank you very much for the update

**Pull request merged**
