### PR TITLE
Round #9 submission UNCC

### PR DESCRIPTION
**Pull request by lunarmouse**
## Description

Please include a brief description of your change.  

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: 
- Model Name: 
- Institution:  
---

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new scenarios** to an existing model, please include the following details:- 
- Team name: UNCC
- Model name that is being updated:  Hierbin
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @lunarmouse ,

Thank you for your pull-request, I saw that you submit two zip files and one is outside of the data-processed folder. Should we use the file inside the `data-processed` folder and if so, is it possible to remove the other one? 
Please feel free to let me know if you have any questions,

Best,
Lucie

**Comment by lunarmouse** [comment]
Hi Lucie thanks for the  heads up. The files are identical (one was uploaded by error), so I removed the outside one. Now there should be only one file in the /dataprocessed folder.

**Comment by lunarmouse** [comment]
Hi @LucieContamin thanks for the heads up. The files are identical (one was uploaded by error), so I removed the outside one. Now there should be only one file in the /dataprocessed folder.

**Comment by LucieContamin** [comment]
Thank you very much for the update. 
Best,
Lucie

**Pull request merged**
