### PR TITLE
CU round 6

### PR DESCRIPTION
**Pull request by tkcy**
## Description

Please include a brief description of your change.  

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: 
- Model Name: 
- Institution:  
---

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new scenarios** to an existing model, please include the following details:- 
- Team name: 
- Model name that is being updated:  
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @tkcy ,

Thank you for your pull-request,

It seems that the scenario id in the column scenario_id do not correspond to the scenario_id for the round 6, would it be possible to verify it, please? The information can be found on the README.
Please feel free to let me know if you have any questions or if I can be of further assistance.

Thanks,
Lucie

**Comment by LucieContamin** [comment]
Also, it looks like the pull-request contains projections for all the targets except the cumulative hospitalization. Could I ask if it would it be possible to add the `cum_hosp` target?
Thanks,
Lucie

**Comment by tkcy** [comment]
Thanks, I changed the date from 5/30 to 6/8.

We don't currently produce cumulative hospitalizations.

**Comment by LucieContamin** [comment]
Thank you for the update and for the information.

**Pull request merged**
