### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by MPS7**
## Description

Submission of round 13 projections for  6 states: Florida, Texas, California, New York, Illinois, and Massachusetts.

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: UTA-ImmunoSEIRS
- Model Name: ImmunoSEIRS
- Institution:  UT COVID-19 Modeling Consortium.
---

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new scenarios** to an existing model, please include the following details:- 
- Team name: 
- Model name that is being updated:  
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Scenario-File-Checks).

### CODE REVIEW

**Comment by MPS7** [comment]
After a failed validation test, I corrected the name of the file.

**Comment by MPS7** [comment]
Corrected Florida cumulative cases

**Comment by LucieContamin** [comment]
Hi @MPS7 ,

Thank you very much for the submission and for the updates.
I have a question about the abstract, it seems that some sections are not corresponding to the abstract template for round 13. Would it be possible to update it to match the template, please? The template can be found [here](https://github.com/midas-network/covid19-scenario-modeling-hub/blob/master/data-processed/MyTeam-MyModel/2022-03-13-MyTeam-MyModal-Abstract.md).

Please feel free to let me know if you have any questions or troubles,

Best,

Lucie

**Comment by MPS7** [comment]
Hi Lucie,

Thank you for the remark. I have updated the abstract according to R13 format.

Best regards,
Anass

**Comment by LucieContamin** [comment]
Hi Anass,

Thank you very much for the update, just for information I manually cancel the validation as the update was only on the abstract so please feel free to ignore the last checks results.
I have a quick question about the abstract update, I cannot see the section "Number/type of immune classes considered" and "Other", should I consider them as empty? And if so, would it be possible to include the "Number/type of immune classes considered" section?
Also, as the "Model assumptions" is not a section to FILL, would it be possible to move the information to another section (other for example?)? 

Best,

Lucie

**Comment by MPS7** [comment]
Hi Lucie,

Sorry for the delayed response. I have added the section on the number and type of immune classes to the abstract. 

Best regards,
Anass

**Comment by LucieContamin** [comment]
Hi Anass,

Thank you for the update, I will merge the PR.

Best,
Lucie

**Pull request merged**
