### PR TITLE
UNC Charlotte Round 18 submission with age information

### PR DESCRIPTION
**Pull request by lunarmouse**
## Description

Please include a brief description of your change.  

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: 
- Model Name: 
- Institution:  
---

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new scenarios** to an existing model, please include the following details:- 
- Team name: UNC Charlotte (formerly UNCC)
- Model name that is being updated:  Hierbin
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Scenario-File-Checks).

### CODE REVIEW

**Comment by lunarmouse** [comment]
Hi @LucieContamin Lucie, received an error message but not sure what caused the error... Could you please take a look and let me know what could have gone wrong? Thanks very much, SC

**Comment by LucieContamin** [comment]
Hi @lunarmouse , Thank you for the update. It seems to be on the GitHub Action side, I will look into it. 
In the meantime, I ran the validation manually and here is the results of the validation:

Run validation on files: 2024-04-28-UNCC-hierbin.gz.parquet

 ## Columns: 
 No errors or warnings found on the column names and numbers  

## Scenarios: 
 No errors or warnings found on scenario name and scenario id columns 

## Origin Date Column:  
 No errors or warnings found on the column 'origin_date' 

## Value and Type Columns: 
 ❌ Error 510: Each group combination should have one unique value. 9734400 unique groups have been identified with this issue. For example:
group:  2024-04-28, A-2024-03-01, 01, inc hosp, 1, 0-130, sample, 1; 
group:  2024-04-28, A-2024-03-01, 01, inc hosp, 2, 0-130, sample, 1; 
group:  2024-04-28, A-2024-03-01, 01, inc hosp, 3, 0-130, sample, 1; 
etc. 

## Target Columns: 
 🟡 Warning 602: No value found associated with the targets: inc death (optional), inc hosp (optional), cum death (optional), cum hosp (optional); output_type: quantile, mean. 

## Locations: 
 No errors or warnings found on Location 

## Sample: 
 No errors or warnings found on Sample 

## Quantiles: 
 No errors or warnings found on quantiles values and format 

## Age Group: 
 ❌ Error 802: The `age_group` column contains unexpected value: '0-65'. 'age_group' can only be: 0-130, 65-130, 0-64, for the target: inc death, inc hosp.
❌ Error 802: The `age_group` column is missing at least 1 required value: '0-64'. 'age_group' should contain: 0-130, 65-130, 0-64, for the target: inc death, inc hosp.

**Comment by lunarmouse** [comment]
Hi @LucieContamin Lucie thanks for the feedback. Will fix these issues soon.

**Comment by LucieContamin** [comment]
Hi @lunarmouse , 

Can I ask why did you delete your submission file? Did you wish to be removed from the R18?

Thanks,
Lucie

**Comment by lunarmouse** [comment]
Hi Lucie @LucieContamin I found some issues in death projections and will upload a new one soon. Thanks!

**Comment by lunarmouse** [comment]
Oh Lucie @LucieContamin I just realized that I directly deleted the file on the midas repo instead of my own repo via pull request.... Sorry about that from a lunar mouse at 3am!

**Comment by LucieContamin** [comment]
> Oh Lucie @LucieContamin I just realized that I directly deleted the file on the midas repo instead of my own repo via pull request.... Sorry about that from a lunar mouse at 3am!

It's not a problem at all it was in your PR so on your forked repo. I was just wondering if I was missing some information.

**Comment by LucieContamin** [comment]
Please let me know when you have your final version, so I can merge it. Thanks!

**Comment by lunarmouse** [comment]
Hi Lucie @LucieContamin the most recent PR around 3:45 should be the final version. Hopefully no more bugs. Thanks! SC

**Comment by LucieContamin** [comment]
Perfect! Thanks for the update! I will merge it soon! 
Best, Lucie

**Pull request merged**
