### PR TITLE
Round 18 UNC Charlotte Hierbin

### PR DESCRIPTION
**Pull request by lunarmouse**
Hospitalization projections only. Still tweaking on death.

## Description

Please include a brief description of your change.  

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: 
- Model Name: 
- Institution:  
---

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new scenarios** to an existing model, please include the following details:- 
- Team name: UNC Charlotte (UNCC)
- Model name that is being updated:  Hierbin
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Scenario-File-Checks).

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @lunarmouse ,

Thank you for your submission. The validation did not run completely because the date in the filename and the origin_date column should correspond to: "The date YYYY-MM-DD should correspond to the start date for scenarios projection ("first date of simulated transmission/outcomes" as noted in the scenario description on the main [README, Submission Information](https://github.com/midas-network/covid19-scenario-modeling-hub#submission-information))." So, here it will be `"2024-04-28"`. 

Please let me know if any other issues or questions,

Best, Lucie

**Comment by LucieContamin** [comment]
Just to add more information on the last validation run. The submission format has changed, please refer to the [Model Results File Format](https://github.com/midas-network/covid19-scenario-modeling-hub/tree/master/data-processed#model-results-file-format) section in the associated README.

Please feel free to let me know if any issues or questions,

Best, Lucie

**Comment by lunarmouse** [comment]
Thanks Lucie, just want to confirm, is age group required (<65 and >65 and all) for this round #18?

**Comment by LucieContamin** [comment]
The three age groups are required, so the validation will return an error if they are missing. However, I can ignore that error and we will accept a submission with only the overall population. 

Please feel free to let me know if any issues or questions,
Best, Lucie

**Comment by lunarmouse** [comment]
Hi Lucie, could you please accept this pull request as I plan to provide age group specific projections by the weekend. This submission has overall age (0-130) to validate the results. Please let me know if I need to pull again. Thanks! SC

**Comment by LucieContamin** [comment]
HIi @lunarmouse ,

Thank you for the update, I just wanted to verify that I understand the pairing information in the sample correctly. According to your submission, each model run has different run_grouping (model run independent) for every stochastic run, grouped by `age_group`,  `horizon`, `scenario`, `location`, `target`, am I correct?

Thanks, 
Lucie

**Comment by lunarmouse** [comment]
Hi Lucie, yes the grouping is grouped by horizon, scenario, location, and target. When I further process age-specific projections, age_group will also be part of the group as well. Thanks for checking in! SC

**Pull request merged**
