### PR TITLE
Preliminary results for scenario 11 from NotreDame-FRED 

### PR DESCRIPTION
**Pull request by confunguido**
## Description

These are the results we have so far for the State of Indiana. Given the timeline, we might not be able to submit more states. 

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new scenarios** to an existing model, please include the following details:- 
- Team name: Notre Dame
- Model name that is being updated:  NotreDame-FRED
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by harryhoch** [comment]
do you have any changes to the metadata?

**Comment by confunguido** [comment]
> do you have any changes to the metadata?

For this round, we did not make changes in the model, other than what was already specified in the scenario 11. So, we did not consider necessary updating the metadata, since the implementation of omicron was done in a similar way of round 9. If necessary, I can update the metadata accordingly.

**Comment by harryhoch** [comment]
ok. no need for new meatada.

**Comment by harryhoch** [comment]
the end of the first projection week should be 2021-12-15, not 2021-12-24

**Comment by confunguido** [comment]
> the end of the first projection week should be 2021-12-15, not 2021-12-24

Thank you. Just to clarify. Should the first week be Dec 25th or Dec 15th? I thought the data would go until Dec 18.

**Comment by harryhoch** [comment]
my typo - december 25.

**Pull request merged**
