### PR TITLE
Submitting round 9 projections - USC SIkJalpha

### PR DESCRIPTION
**Pull request by scc-usc**
## Description

Submitting round 9 projections. Also, updated meta data to reflect changes in modeling.

Thanks,
Ajitesh

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: 
- Model Name: 
- Institution:  
---

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new scenarios** to an existing model, please include the following details:- 
- Team name: 
- Model name that is being updated:  
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @scc-usc ,

Thank you for the pull-request, 
It all looks good, however there was a typo in the README about the scenario name. We fixed it this morning. The scenario "C-2021-09-14" has been changed to `"ChildVax_Var"` instead of `"ChildVax_noVa"`. Would it be possible to update the scenario name in your csv file, please? I apologize for the inconvenience. 

Thanks and please don't hesitate to let me know if you have any questions or if I can be of further assistance.

Best,
Lucie

**Comment by scc-usc** [comment]
Hi Lucie,

I am out of town this week and may not have remote access to my machine. I am not sure yet if I will be able to make the change.

Thanks,
Ajitesh

> Hi @scc-usc ,
> 
> Thank you for the pull-request,
> It all looks good, however there was a typo in the README about the scenario name. We fixed it this morning. The scenario "C-2021-09-14" has been changed to `"ChildVax_Var"` instead of `"ChildVax_noVa"`. Would it be possible to update the scenario name in your csv file, please? I apologize for the inconvenience.
> 
> Thanks and please don't hesitate to let me know if you have any questions or if I can be of further assistance.
> 
> Best,
> Lucie

**Comment by LucieContamin** [comment]
Hi Ajitesh,

Thanks for your reply, 
I can help by making the change while merging your pull-request, if that's ok for you. 

Thanks,
Lucie

**Comment by scc-usc** [comment]
Hi Lucie,

That will be fantastic. Thank you very much.

Ajitesh

**Comment by LucieContamin** [comment]
Hi Ajitesh,

Thank you very much again for your reply and for your pull-request, I will make the change after merging.
Best,
Lucie

**Pull request merged**
