### PR TITLE
UTA-ImmunoSEIRS Results of round 15

### PR DESCRIPTION
**Pull request by MPS7**
Hi, 

This is our projections file for round 15. There might be some errors in cumulative numbers so I will update them by July 31, 2022.

Thank you.

Best regards,
Anass

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi Anass, 

Thank you for the pull-request. The validation is currently being updated for the round 15, so please feel free to ignore the errors 601 and 605. I apologize for the inconvenience.
Please let me know if any questions or issues,

Thanks,

Lucie

**Comment by LucieContamin** [comment]
Hi again 

Thank you for the quick update. The validation is still being updated for the round 15, so please feel free to ignore the errors 601 and 605. I apologize for the inconvenience. I will take the validation as accepted. 
Please let me know if any questions or issues,

Thanks,

Lucie

**Comment by MPS7** [comment]
Hi Lucie, 

Thank you very much for running the validation checks. I have updated the results. Hopefully, they will go without errors this time.

Best regards,
Anass

**Comment by LucieContamin** [comment]
Thanks again Anass, 
It looks all good so I will merge the PR beginning next week.

Best, Lucie

**Pull request merged**
