### PR TITLE
CU Round 7 submission

### PR DESCRIPTION
**Pull request by tkcy**
## Description

Please include a brief description of your change.  

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: 
- Model Name: 
- Institution:  
---

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new scenarios** to an existing model, please include the following details:- 
- Team name: 
- Model name that is being updated:  
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @tkcy ,

Thank you for your submission,

I have a question about the projections file, I notice that your 1 week target is on the 2021-07-24 but according to the information on the GitHub for the round 7, it should be on the 2021-07-10, would it be possible to verify it please?

Please don't hesitate to contact me if you have any questions or if I can be of further assistance.

Thanks,
Lucie

**Comment by tkcy** [comment]
@LucieContamin thanks, should be fixed now

**Comment by LucieContamin** [comment]
@tkcy , thank you very much for the update. 
However, it looks like the first version if the file is still in the `data-processed/CU-AGE-ST/` folder and the update version is not in the folder, would it be possible to update it, please? 
Thanks,
Lucie

**Comment by tkcy** [comment]
@LucieContamin sorry, I had it in the wrong spot.  hopefully good now!

**Comment by LucieContamin** [comment]
@tkcy, thank you for the update, it looks all good now!

**Pull request merged**
