### PR TITLE
CU round 5

### PR DESCRIPTION
**Pull request by tkcy**
## Description

Please include a brief description of your change.  

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: CU
- Model Name: AGE-ST
- Institution:  Columbia
---

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new scenarios** to an existing model, please include the following details:- 
- Team name: 
- Model name that is being updated:  
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @tkcy ,

Thank you for your pull-request.
I have a question about the projection you submitted. The file you attached seems to contain projections for the "incidence" targets (inc case, inc death, inc hosp). Could I ask how long it would take to provide projections the "cumulative" targets (cum case, cum death, cum hosp) and if it would it be possible to add it?

Thanks also for the metadata file. We use a special format for it, you can find information here: https://github.com/midas-network/covid19-scenario-modeling-hub/blob/master/data-processed/METADATA.md. Would it be possible to update your metadata file to this format, please? For additional information, we will accept a file without the fields that have "Not applicable" as possible values. By default, we will consider all these missing fields with the value "Not applicable".

Please, feel free to let me know if you have any questions or if I can be of further assistance.

Thanks,
Lucie

**Comment by tkcy** [comment]
Hi! I added cumulative deaths and incidence. Hospitalizations would take more time so I will omit those for now.  We'll update the metadata shortly.

**Comment by tkcy** [comment]
@LucieContamin just making sure you saw there was an update to our cumulative cases and deaths

**Comment by LucieContamin** [comment]
Hi, thank you for all the updates!

**Pull request merged**
