### PR TITLE
Notre Dame - FRED round 12

### PR DESCRIPTION
**Pull request by confunguido**
## Description

Please include a brief description of your change.  

If you are **adding new scenarios** to an existing model, please include the following details:- 
- Team name: NotreDame
- Model name that is being updated:  NotreDame-FRED
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @confunguido ,

Thank you for your submission, I just have a quick questions. It seems that the scenario id name does not correspond to the scenario id as specify on the GitHub README for Round 12, for example, the scenario A should be A-2021-01-09. Would it be possible to update it, please?

Please feel free to let me know if you have any questions or troubles,

Best,
Lucie Contamin

**Comment by confunguido** [comment]
Hi Lucie, 

Thank you for letting me know. I'm sorry about that issue. I'll update it and resubmit. 
Thanks,
Guido

**Comment by confunguido** [comment]
I updated the scenario_id values. Please let me know if there's anything else I should update. 

Thanks,
Guido

**Comment by LucieContamin** [comment]
Hi Guido, 

It looks all good, thank you very much for the quick update.

Best,
Lucie

**Pull request merged**
