### PR TITLE
UNCC Hierbin Round 15

### PR DESCRIPTION
**Pull request by lunarmouse**
## Description

Please include a brief description of your change.  

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: 
- Model Name: 
- Institution:  
---

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new scenarios** to an existing model, please include the following details:- 
- Team name: UNCC
- Model name that is being updated:  Hierbin
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Scenario-File-Checks).

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @lunarmouse ,

Thank you for your submission.
It seems that the validation did not run properly, I apologize for the inconvenience. 
I run the validation locally and it seems to contains some issues:
- the name of the files should be "2022-07-31-UNCC-hierbin.csv.zip" and  "2022-07-31-UNCC-hierbin-abstract.md", would it be possible to update it please?
- the abstract for the round 15 is slightly different than round 14, would it be possible to update it, please? here is the link to round 15 abstract: https://github.com/midas-network/covid19-scenario-modeling-hub/blob/master/data-processed/MyTeam-MyModel/2022-07-31-MyTeam-MyModel-Abstract.md 
- it seems that the submission contains value only the "1 wk ahead inc case", the rest of the files seem to be all `NA`, would it be possible to verify that, please?

If you have any questions or need more information, please feel free to let me know,

Thanks,
Lucie

**Comment by lunarmouse** [comment]
Hi @LucieContamin thanks for the heads up! I have updated the following as you suggested:
1. Corrected file names (both submission file and abstract)
2. Updated abstract with the latest template
3. Fixed issues of NAs in the submission file -- thanks for pointing this out! I accidentally forget to apply "which" to extract row numbers. I double checked the submission file, and it should look fine now.
All the best,
Shi

**Comment by LucieContamin** [comment]
Hi Shi,

Thank you very much for the update, it looks all good. Just a minor issue, the name of the file should be without V2, for example: "2022-07-31-UNCC-hierbin.csv.zip" or it will be counted as a new model. Would it be possible to update it please or should I take it as a new model?

Thanks,
Lucie

**Comment by lunarmouse** [comment]
Hi Lucie sure, I updated the submission file with the correct file name (without V2).

**Comment by LucieContamin** [comment]
Perfect, thank you very much! I will merge the PR today. 

Best,
Lucie

**Pull request merged**
