### PR TITLE
Update Dec scenarios and add Jan (2nd round) scenarios for USC-SIkJalpha

### PR DESCRIPTION
**Pull request by scc-usc**
## Description

I am updating the output of the first round of scenarios for data up to Jan 23rd.
Also, submitting the second round of scenarios. 
Since the combined file was too large I am submitting two separate files with suffix _Dec and _Jan, representing the month of origin of the scenarios.

---

## Checklist

- [x ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @scc-usc ,

Thank you for your pull-request.
As I understand, the file with the suffix `_Dec` contains data for the scenario from December and the file with the suffix `_Jan` contains data for the scenario from January. However, the `_Jan` file contains the `scenario_name` for January but the column `scenario_id` contains identifier for the scenario from December and January. Would it be possible to please verify it?

Thanks,
Lucie

**Comment by scc-usc** [comment]
Hi Lucie,

Thanks for pointing it out. There was an error in naming the scenario ids for the US country-level in _Jan.csv file. I have fixed it. 
Now, _Dec file should only contain scenarios declared in Dec, and _Jan file should only contain scenarios declared in January.

Thanks,
Ajitesh

**Comment by LucieContamin** [comment]
Hi Ajitesh,

Thank you for the update. 
I understand that the combined file is too large to be submitted. So, to inform you, we will accept the combined file in the `zip` format. For this pull-request I can merge it and merge the two files together in a `zip` format. 

Please feel free to let me know if you have any questions,
Many thanks,

Lucie

**Comment by scc-usc** [comment]
Thanks, Lucie. Next time, I will submit a zipped combined file.

Ajitesh

**Comment by LucieContamin** [comment]
No submission file in the standard  SMH file format found in the Pull-Request.

**Comment by LucieContamin** [comment]
No submission file in the standard  SMH file format found in the Pull-Request.

**Comment by LucieContamin** [comment]
No submission file in the standard  SMH file format found in the Pull-Request.

**Pull request merged**
