### PR TITLE
Updated round 18 projections to include age groups

### PR DESCRIPTION
**Pull request by mooresea**
## Description

Added required age group projections. Increased number of trajectories per scenario from 100 to 200.

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Scenario-File-Checks).

### CODE REVIEW

**Comment by LucieContamin** [comment]
Good afternoon @mooresea ,

If I can provide more information on the error messages: it seems that the main issue is the `NA` in the `age_group` column for the `sample` output type. It creates multiple errors that might be confusing in the validation report. Also as I reminder, it is important to have the same number of samples for every group. 

Please let me know if any issue or questions,
Best, 
Lucie

**Comment by mooresea** [comment]
Lucie,

Thank you, I think I have fixed the issue with NAs in the age_group column.
Unfortunately, I am in Nairobi this week and my internet connection may not
be strong enough to download my projections to my laptop for processing and
then upload them to github until next week.

Sean

**Comment by LucieContamin** [comment]
Hi @mooresea ,

Thank you for the update, I have a question about your submission, it seems that the file contains "sample" and "quantile" output type for all targets: cumulative and incident hospitalization and death. However, I noticed that your files do not contain cumulative hospitalization and death samples for the age group "0-130" but it's available for other age group. As the targets are optional, the validation did not send a message, but would it be possible to look into it, please?
I am happy to wait next week for next update if it's easier.

Please let me know if any issue or questions,
Best,
Lucie

**Comment by LucieContamin** [comment]
Hi again!

Sorry for the double message, but will it also be possible to remove your previous submission files to avoid issues. 
Please let me know if any issue or questions,
Best,
Lucie

**Comment by LucieContamin** [comment]
Hi @mooresea,
Thank you for the update, it looks all good now.
Best, Lucie

**Pull request merged**
