### PR TITLE
Preliminary projections for scenario 10 of NotreDame-FRED team

### PR DESCRIPTION
**Pull request by confunguido**
## Description

Please include a brief description of your change.  
 does not apply to you, please delete it in your PR_  

If you are **adding new scenarios** to an existing model, please include the following details:- 
- Team name: NotreDame
- Model name that is being updated:  NotreDame-FRED
---

## Checklist

- [x] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by LucieContamin** [comment]
Good morning @confunguido ,

To follow up on the update of the submission information on the "end date for fitting data" and "start date for scenarios", could I ask if you plan to submit an update? 
If any problems or questions, please feel free to let me know, I will be happy to help.

Best,
Lucie

**Comment by confunguido** [comment]
Hi. Given how busy this week looks for us, I don't think we'll be able to change the dates. We might update that later if possible.

**Comment by LucieContamin** [comment]
Hi @confunguido ,

I apologize for the confusion, as the due date is on the 3rd/6th of December, please feel free to take your time and enjoy a break this week and update later. 
It was to inform you that as the submission information has changed, I am not going to merge this first version yet and will wait for an update later. 

I apologize again for the confusion and please feel free to let me know if you have any questions or troubles, I will be happy to help.

Best,
Lucie

**Comment by confunguido** [comment]
Hi @LucieContamin ,

I updated the calibration/projection with the updated dates. Please let me know if things look okay. 

Best,
Guido

**Comment by LucieContamin** [comment]
Hi @confunguido 

Thank you very much for your update, I have some questions about it.

It seems that the target_end_date values in your projections are on a Friday. For "# wk" targets, the target_end_date should be the Saturday at the end of the week time period. You can find more information on this page: https://github.com/midas-network/covid19-scenario-modeling-hub/tree/master/data-processed#target_end_date. Also, as the start date for scenarios is November 14 (first date of simulated transmission/outcomes), the 1 week target should one November, 20. Would it be possible to verify and update it, please?

Also, it seems that the projections you submitted are for the cumulative and incident deaths and cases for Indiana, am I correct or did I misread the file? If so, could I ask if you are also planning to submit projections at national level and/or other states and/or other targets?

Thanks and please don't hesitate to let me know if you have any questions or if I can be of further assistance.

Best,
Lucie

**Comment by confunguido** [comment]
Thanks! I'm looking into that. It seems like there was an issue with the post-processing scripts.

**Comment by confunguido** [comment]
I updated the dates. Hopefully this time is alright. The first target end date is Nov 20. I thought we had cases and deaths in the targets. Unfortunately, we might not be able to submit more states/targets other than Indiana before the deadline, but we'll try.

**Comment by LucieContamin** [comment]
Thanks! 
I apologize for the multiple messages but would it be possible to also update the metadata, so the field correspond to the standard fields (please find more information here: https://github.com/midas-network/covid19-scenario-modeling-hub/blob/master/data-processed/METADATA.md) and remove the "old" projection file you previously submit for round 10 to avoid confusion. 

I apologize again for the confusion and please feel free to let me know if you have any questions or troubles, I will be happy to help.

Best,
Lucie

**Comment by confunguido** [comment]
I thought I had deleted the previous file. Let me know if that's not the case. Also, is there any specific field that's not in the right format? I thought we were adhering to the metadata format. 

Thanks!

**Comment by LucieContamin** [comment]
It seems that the pull-request still contains the "2021-11-09" files. And, for the metadata, the format is good is just that the "future_NPI" is not a field in the original scheme, would it be possible to merge it with another field, please?

Many thanks,

Lucie

**Comment by confunguido** [comment]
I hope it's fixed now.

**Comment by LucieContamin** [comment]
@confunguido , everything looks good. Thank you very much for the update.

**Pull request merged**
