### PR TITLE
CFA Round 18 Submission

### PR DESCRIPTION
**Pull request by arik-shurygin**
## Description
Submission does **not** include deaths, only incident hospitalizations.

- Team name: CFA
- Model Name: Scenarios
- Institution:  CDC Center for Forecasting and Outbreak Analytics

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @arik-shurygin .

Thank you for your submission and welcome! I just wanted to verify that I understand correctly the sample ID numbering: there is no stochasticity, every models runs has a different `run_grouping` "grouped" by age_group, location, horizon, scenario_id, and, target. Is that correct?

Please let me know if any issues or questions,
Best, Lucie

**Comment by LucieContamin** [comment]
Also, thank you for the abstract, but would it be possible to re-format it to match the previous abstract format, please? You can find the information here: https://github.com/midas-network/covid19-scenario-modeling-hub/blob/master/data-processed/MyTeam-MyModel/2023-04-16-MyTeam-MyModel-Abstract.md

Please let me know if any issues or questions,
Best, Lucie

**Comment by tjhladish** [comment]
Hi @LucieContamin, would it be possible to set up a time to discuss how our replicates should be matched?  I want to make sure that there's no confusion resulting from using terminology differently, etc.

**Comment by eahowerton** [comment]
Hi @tjhladish, we'd be happy to schedule a call to discuss. l just sent you an email with a few proposed times.

**Comment by LucieContamin** [comment]
Hi @arik-shurygin ,

Thank you for the update. Can I ask what the difference with the first submission? 
Also, just for information, I will update the abstract for R18 today and will be happy to update the information in this PR as soon as available.

Please feel free to let me know if any questions or issues,
Best,
Lucie

**Comment by LucieContamin** [comment]
Please find here the skeleton for the R18 abstract: https://github.com/midas-network/covid19-scenario-modeling-hub/blob/master/data-processed/MyTeam-MyModel/2024-04-28-MyTeam-MyModel-Abstract.md 
Please feel free to let me know if any questions or issues,
Best,
Lucie

**Comment by arik-shurygin** [comment]
> Hi @arik-shurygin ,
> 
> Thank you for the update. Can I ask what the difference with the first submission? Also, just for information, I will update the abstract for R18 today and will be happy to update the information in this PR as soon as available.
> 
> Please feel free to let me know if any questions or issues, Best, Lucie

Hey Lucie.

This commit is an updated parquet submission, we are still working on an updated abstract but figured we would send the updated data the moment we had it.

There will likely be another update to this Pull Request once the abstract/metadata are updated.

**Comment by tjhladish** [comment]
> Hi @arik-shurygin ,
> 
> Thank you for the update. Can I ask what the difference with the first submission? Also, just for information, I will update the abstract for R18 today and will be happy to update the information in this PR as soon as available.
> 
> Please feel free to let me know if any questions or issues, Best, Lucie

Hi @LucieContamin, we noticed some problems with the timing of vaccine uptake during the fitting period, that in turn affected the parameter estimates and initial conditions used for the projection period.  We have now re-run everything.

We're also including Hawaii now; it still is not a compelling projection, but it seems less clearly wrong than it was in our first results version.

Thanks,
Tom

**Comment by LucieContamin** [comment]
Thank you very much for the additional information.
I will keep the PR open for the updated abstract.

Please feel free to let me know if any questions or issues,
Best,
Lucie

**Comment by LucieContamin** [comment]
Good morning,

Thank you for the abstract update. I see that it matches the R17 skeleton. I apologize if I was confusing but we updated the skeleton since last week, to a R18 specific. I updated the link in the PR but here it is: https://github.com/midas-network/covid19-scenario-modeling-hub/blob/master/data-processed/MyTeam-MyModel/2024-04-28-MyTeam-MyModel-Abstract.md Would it be possible to update to that format? 

Please feel free to let me know if any questions or issues,
Best,
Lucie

**Comment by LucieContamin** [comment]
Hi,

Thank you for the abstract update! I just have some minor questions and should be able to merge.
In the abstract: 
- the section number/types of immune classes considered has been removed. However it's still present in the round 18. Your previous version contains the information:
```
# Number/type of immune classes considered 

Immune classes are stratified by infection history ($2^7$ possible histories, caused by 3 ancestral strains and 4 introduced during the projection) and vaccination history (0, 1, or 2+ doses of earlier vaccines, and seasonally vaccinated with the new vaccine during the projection).  Waning occurs across four bins; any kind of immunogenic event (infection or vaccination) moves people back to the least-waned bin. 
```

- Some sections titles are missing some information, for example `Seasonality implementation` instead of `Seasonality implementation, e.g., whether seasonality varies by geography and which datasets are used to fit seasonal parameters`

It's minor issue and I am happy to merge the PR as it is and update the abstract after by adding the missing information back and updating the title sections , if it's easier for you. However, if you prefer to add/edit the abstract directly, please let me know and I will keep the PR open.

Please feel free to let me know if any questions or issues,
Best,
Lucie

**Comment by tjhladish** [comment]
@LucieContamin please check if the abstract looks right now

**Comment by LucieContamin** [comment]
Thank you very much for the update, it looks all good! I will merge the PR. 

Thanks again, Lucie

**Pull request merged**
