### PR TITLE
MOBS_NEU-GLEAM_COVID Submission

### PR DESCRIPTION
**Pull request by jessica-davis**
## Description

- Team name: MOBS_NEU
- Model name that is being updated:  GLEAM_COVID

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @jessica-davis ,

Thank you for the submission. I just wanted to check I understand correctly the sample ID numbering: each model runs has different `run_grouping` (model run independent) for every `stochastic_run` group by `age_group`,  `horizon`, and sub-group of scenario (group I: `A`, `C`, `E`; group II: `B`, `D`, `F`). Is that correct?

Please let me know if any issues or questions,
Best,
Lucie

**Comment by jessica-davis** [comment]
Hi @LucieContamin, I think you are correct. Essentially there is a new stochastic_run/ run_grouping id for each sample and location combination that connects the age_group, horizon, and scenario sub-group (ACE and BDF). This means that when comparing the effects of the vaccine strategy  within either the ACE or BDF scenarios (not across) and you can compare the trajectories that were run with the same random seed and initial conditions in our model (so the only change is the vaccine uptake in 2024/25). Is there a different way I should have done the run_grouping/ stochastic run numbering? Please let me know, and I'm happy to update the file if it makes things easier.

Thanks!
Jessica

**Comment by LucieContamin** [comment]
Hi @jessica-davis , Thank you for the confirmation and the additional information. It sounds all good to me! 

Thanks again,
Lucie

**Comment by LucieContamin** [comment]
Hi @jessica-davis ,

I apologize for the late message. but I have a question about the pairing of your submission. It seems that I made a mistake and miss one pairing level: `target`, sorry about that. But I wanted to confirm that I have the good representation now, so as I understand: 
- `run_grouping` and `stochastic_run` are grouped by: `age_group`, `horizon`, sub-group of `scenario_id` (either ACE or BDF) and `target`. Is that correct?

Thanks, 
Best,
Lucie

**Comment by jessica-davis** [comment]
Hi Lucie, I'm sorry, I also forgot about the target column. It is grouped with the columns you listed, so that is correct.

**Comment by LucieContamin** [comment]
Perfect, thank you very much for the quick reply and confirmation.

**Pull request merged**
