### PR TITLE
NCSU-COVSIM Round 12 Submission

### PR DESCRIPTION
**Pull request by erosenstrom**
## Description

NCSU-COVSIM Round 12 Submission

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: NCSU
- Model Name: COVSIM
- Institution:  North Carolina State University
---

## Checklist

- [x ] Specify a proper PR title with your team name.
- [x ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @erosenstrom ,

Thank you for your submission, I just have a small remark, It seems that the dates inside your file are in the `M/DD/YYYY` format, would it be possible to change the date format to `YYYY-MM-DD` please? 
Also I just wanted to verify if the metadata file you submitted for Round 11 is the same for Round 12 or should it be updated? 

Best,
Lucie

**Comment by erosenstrom** [comment]
I have uploaded the correct  csv and a new metadata file

**Comment by LucieContamin** [comment]
Thank you very much for the quick update! It looks all good now. 

However it seems that the metadata files is having a conflict. It might be because I removed your previous submission manually as it was not included in the Round 11. I apologize for the trouble. 
Would it be possible to remove the metadata file from the pull-request and I will update it manually, please? 
And to avoid future trouble, it might be easier to update or fork again this repository after I merge your pull-request.

Please feel free to let me know if you have any questions or troubles,

Many thanks,

Lucie

**Comment by LucieContamin** [comment]
Thank you very much again for the quick update!

Best,
Lucie

**Pull request merged**
