### PR TITLE
UNCC HierBin Round #7 update

### PR DESCRIPTION
**Pull request by lunarmouse**
## Description

Please include a brief description of your change.  
Updated model fitting and simulation to fix discrepancy issue.

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: 
- Model Name: 
- Institution:  
---

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new scenarios** to an existing model, please include the following details:- 
- Team name: UNCC
- Model name that is being updated:  Hierbin
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by lunarmouse** [comment]
Updated with new model fitting to solve initial condition discrepancy issue.

**Comment by LucieContamin** [comment]
Hi @lunarmouse ,

Thank you for the update.
However, I have some questions for the file `2021-06-09-UNCC-hierbin.csv.zip`. It seems that the column `scenario_id` does not contains the scenario id values for round 6, would it be possible to verify it, please? Also, the column `target` seems to contains only one value `26 wk ahead inc case`, is it possible to check it please?

Please feel free to let me know if any questions,

Best,

Lucie

**Comment by lunarmouse** [comment]
Updated scenario_id and corrected target in V6 (06-08).

**Comment by LucieContamin** [comment]
Thank you for the update

**Pull request merged**
