### PR TITLE
UNCC Round #10

### PR DESCRIPTION
**Pull request by lunarmouse**
## Description

Please include a brief description of your change.  

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: 
- Model Name: 
- Institution:  
---

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new scenarios** to an existing model, please include the following details:- 
- Team name: UNCC
- Model name that is being updated:  Hierbin
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @lunarmouse ,

Thank you for the pull-request.

I have some questions about the target dates. It seems that your 1 week target is on the 2021-11-07, am I correct? As the start date for scenarios is November 7th (first date of simulated transmission/outcomes), the 1 week target should on the 2021-11-13. Would it be possible to verify and update it, please?
Also, it looks like some of your location are missing a trailing "0", for example "1" instead of "01".  Would it be possible to verify and update it too, please?

If any problems or questions, please feel free to let me know,

Best,
Lucie

**Comment by lunarmouse** [comment]
Hi Lucie thanks for your check. I have updated the file. Thanks!

**Comment by LucieContamin** [comment]
Hi again,

Thank you very much for the update. The target end dates look fine. I just have a quick question about the locations. In the new version of the file, you seem to have the location "03" and "07". However, these locations are not in the `locations.csv` (https://github.com/midas-network/covid19-scenario-modeling-hub/blob/master/data-locations/locations.csv) used for the projections. Would it be possible to verify and update it too, please?

If any problems or questions, please feel free to let me know,

Best,
Lucie

**Comment by lunarmouse** [comment]
Hi Lucie I replaced the 03/07 FIPS with correct ones. Thanks for checking  on this.

**Comment by LucieContamin** [comment]
Hi, thank you very much for the update.

**Pull request merged**
