### PR TITLE
UNCC round10 revision

### PR DESCRIPTION
**Pull request by lunarmouse**
## Description

Please include a brief description of your change.  

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: 
- Model Name: 
- Institution:  
---

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new scenarios** to an existing model, please include the following details:- 
- Team name: UNCC
- Model name that is being updated:  Hierbin
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by lunarmouse** [comment]
Fixed inconsistency issue in hospitalization projections.

**Comment by LucieContamin** [comment]
Hi @lunarmouse ,

Thank you very much for the update, I have a question about the `target_end_date`. 
The "end date for fitting data" and the "start date for scenarios" have been updated on Friday afternoon. The "end date for fitting data" is :  No earlier than Nov 13, 2021 and no later than Nov 20, 2021 and the "Start date for scenarios" is : Nov 14, 2021 which make the 1 week ahead target_end_date on Nov 20, 2021. In your last submission, it seems that the 1 week ahead target_end_date is on Nov 13, 2021, would it be possible to update it please?

Please feel free to let me know if any questions or troubles,

Best,
Lucie

**Comment by lunarmouse** [comment]
Hi @LucieContamin thanks for your heads up. Yes I understand that we will use the updated data, my thoughts is perhaps to update this round for preliminary data and results dissemination before the Thanksgiving break. I will prepare a full revision with new fitting end date on Nov. 20, and project 52wks instead of 26wks and submit by Dec. 2nd. Please let me know which one you think is preferable ( an intermediate update on round #10 with updated hospitalization projection plus a final update, or a final update only on this round by Dec. 2nd). Thanks, Shi

**Comment by LucieContamin** [comment]
Thanks for the additional information. 
I can merge the intermediate update if you think it might be helpful to see the hospitalization projection update. But, we can also wait for the final update if it's preferable for you. 

Please feel free to let me know if any questions or troubles,

Best,
Lucie

**Comment by lunarmouse** [comment]
Hi Lucie, I would like to request the merge of the intermediate update so that I am able to compare projection consistency with other groups while working on the update in round #10. I will send another pull request early December based on the updated instructions. Thanks,
Shi

**Comment by LucieContamin** [comment]
Thank you! It sounds good to me, I will work on merging it this afternoon.
Best,
Lucie

**Comment by lunarmouse** [comment]
Thanks very much for your help! Have a good one,
Shi

**Pull request merged**
