### PR TITLE
CU-Age-ST Round 9 submission

### PR DESCRIPTION
**Pull request by tkcy**
## Description

Please include a brief description of your change.  

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: 
- Model Name: 
- Institution:  
---

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new scenarios** to an existing model, please include the following details:- 
- Team name: 
- Model name that is being updated:  
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @tkcy ,

Thank you for your pull-request,
I have a question about the `scenario_id` and `scenario_name` columns, it seems that the scenario `noChildVax_noVar` is associated with the scenario C and `ChildVax_Var` with scenario B in your file, am I correct? If so, would it be possible to update it to follow the naming as on the Github with scenario B = `noChildVax_noVar` and scenario C = `ChildVax_Var`? 
If any problems or questions, please feel free to let  me know, I will happy to help.

Best,
Lucie

**Comment by tkcy** [comment]
Should be swapped now!

**Comment by rborchering** [comment]
Thank you so much Teresa!!

**Comment by LucieContamin** [comment]
Hi Teresa, 

Thank you very much for the quick update, It looks all good so I will merge your pull-request. 
For information, I will rename the metadata file to follow the standard name and update to the last version of the metadata file you provide. 
Please feel free to let me know if any questions or troubles,

Best, 
Lucie

**Comment by LucieContamin** [comment]
Hi Teresa,

I have another question for your submission, it looks like the 1 week target is on the 2021-09-11, am I correct? As the start date for scenarios is September 12 (first date of simulated transmission/outcomes), the 1 week target should one the 18st of September. Would it be possible to verify and update it, please?
I apologize for the confusion, and please feel free to let me know if any questions or troubles,
Many thanks,

Lucie

**Pull request merged**
