### PR TITLE
Round 12 Results for the University of Texas at Austin

### PR DESCRIPTION
**Pull request by MPS7**
## Description

Results for Round 12 by University of Texas at Austin. We could only make projections for four states: California, Florida, Massachussets, and Texas. Please note that the cumulative hospitalizations do not include the history of hospitalizations up to Jan 8, 2022. We will update the results if we find these data.

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: UT COVID-19 Modeling Consortium
- Model Name: Immuno-SEIRS
- Institution: University of Texas at Austin
---
## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @MPS7 ,

Thank you for your submission and the additional information, and welcome! 

I just have some questions:
- It seems that your submission contains some negative value and no point value. The projections should contains "non-negative numbers" and "must include exactly 1 "point" scenario for every location-target pair" , you can find more information [here](https://github.com/midas-network/covid19-scenario-modeling-hub/tree/master/data-processed#type). But, would it be possible to update your submission to add the point value and remove the negative one, please?
- We also update the `model_projection_date` and Name of the file definition to have a standard between all team, to avoid any technical problem. So the `model_projection_date` and the name of the file should be the same, should be unique, and should correspond to the start date for scenarios (first date of simulated transmission/outcomes). So, for example, for Round 12, it should be `2022-01-09`. You can also find more information [here](https://github.com/midas-network/covid19-scenario-modeling-hub#model-projection-dates). Would it also be possible to update it please?
- I also notice some minor issues: it seems that the file is containing an additional columns contains the row number, would it be possible to remove it, please? I also notice that you submit an empty `readme.md` file, could I ask if you plan to update it or remove it?
- I also wanted to ask if you plan to submit a metadata file containing the information linked to the submission? I cannot add the submission to the hub without a metadata file. You can find more information [here](https://github.com/midas-network/covid19-scenario-modeling-hub/blob/master/data-processed/METADATA.md) and an example of metadata format file [here](https://github.com/midas-network/covid19-scenario-modeling-hub/blob/master/data-processed/MyTeam-MyModel/metadata-MyTeam-MyModel.txt).

Please feel free to let me know if you have any questions, troubles or if I can be of any further help. 

Many thanks,

Lucie

**Comment by MPS7** [comment]
Hi Lucie,

Thank you very much for giving us the opportunity to revise our submission
based on the proposed format. We have corrected the submission based on
your recommendations. The files are attached to this email. For the
abstract, we have updated the file with the format that is provided. The
updated file is attached. We did not prepare any metadata.

Do I need to make a new pull request? I can't seem to find the one that I
made.

Best regards,
Anass

Anass Bouchnita
Postdoctoral Fellow,
University of Texas at Austin,
Austin, Texas,
United States


Le mar. 18 janv. 2022 à 10:00, Lucie Contamin ***@***.***> a
écrit :

**Comment by LucieContamin** [comment]
Hi Anass,

Thanks for your reply and the updates. 
You should be able to edit this pull-request, I have not closed it. However if you prefer to start a new pull-request, you are welcome to close it (or let me know to close it) and create a new one. I did not received the attached files. 

Would it be possible to please submit a metadata text file? 

Please feel free to let me know if you have any questions, troubles or if I can be of any further help.

Best,

Lucie

**Comment by MPS7** [comment]
Hi Lucie,

Thank you for the feedback. I have uploaded the updated projections together with the metadata file. Please let me know if it meets the standards of the scenario modeling hub.

Best regards,
Anass

**Comment by LucieContamin** [comment]
Hi Anass,

Thank you very much for the update and adding the metadata file. 

I just notice some minor issues:
- for the name of the files, for the abstract and CSV file, would it be possible to rename them in the format: "YYYY-MM-DD-teamname-modelname" so for example: "2022-01-09-UTA-ImmunoSEIRS.csv" and "2022-01-09-UTA-ImmunoSEIRS-abstract.md"
- The submission CSV file still contains an additional first column without name that seems to contain the row number, would it be possible to remove it, please? And it seems that the `model_projection_date` column contains multiple value, it should contain only one unique date (same as in the name of the file), for example here it should be `2022-01-09`. Would it be possible to also update it, please?
- For the metadata file, it looks all good, just would it be possible to remove the first 2 lines (the warning message) and start the files at the `team name` lines, please?
- It also seems that your submission contains an empty readme.md file, would it be ok to remove it?

Please feel free to let me know if you have any questions, troubles or if I can be of any further help.

Best,

Lucie

**Comment by MPS7** [comment]
Hi Lucie,

Thank you for pointing out the minor issues. We have changed the files to solve them. The new files are committed. Also, I have removed the empty Readme.md file.

Best regards,
Anass

**Comment by LucieContamin** [comment]
HI Anass,

Thank you very much again for the updates, it looks all good now!

Best,
Lucie

**Pull request merged**
