### PR TITLE
NCSU Round 11 -First Contribution

### PR DESCRIPTION
**Pull request by erosenstrom**
## Description

I have added the round 11 results for North Carolina and the metadata file in our new model folder. This our first submission.

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: NCSU
- Model Name: COVSIM
- Institution:  North Carolina State University
---

## Checklist

- [ x] Specify a proper PR title with your team name.
- [x ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @erosenstrom ,

Thank you for the pull-request.

I have some questions about the target dates. It seems that your 1 week target is on the 2021-12-21, am I correct? As the start date for scenarios is December 19th (first date of simulated transmission/outcomes), the 1 week target should on the 2021-12-25. Would it be possible to verify and update it, please?

I notice the file contains some minor issue that should be easy to fix. I can help if necessary. The file contains an additional columns containing the row number, would it be possible to remove it? 
Also, just to verify I read the file correctly, you submit 20 weeks of projections for 2 targets: "cum death" and "cum hosp" for the location 37, am I correct? If so, as for the round 11 a 12 weeks horizon was expected, we will accept the additional weeks but they are not going to be included in the Ensembles or visualizations. 

If the updates takes too much time or require a rerun, it would be also fine to focus on round 12. 
If any problems or questions or if I can be of any help, please feel free to let me know,

Best,
Lucie

**Comment by erosenstrom** [comment]
I believe I have updated the file correctly. I am new to Github but I think it is now part of this pull request.

**Comment by LucieContamin** [comment]
No problem and thank you very much for the quick update! Will it be possible to remove the "old" file to avoid confusion, please?
If any problems or questions or if I can be of any help, please feel free to let me know,

Best,
Lucie

**Comment by LucieContamin** [comment]
Sorry for the multiple messages but it seems that the new files contains some small issues. 
It seems that the id of the scenarios has been changed to 2021-12-19 instead of 2021-12-21, would it be possible to verify and update if necessary please? The name and id of the scenarios should correspond as written in the [Round 11 README](https://github.com/midas-network/covid19-scenario-modeling-hub/blob/master/previous-rounds/README_Round11.md)

Also, it seems that the files contains the projection for 11 weeks, am I correct? If so, the round 11 contains projections for 12 weeks from 2021-12-25 to 2022-03-12, would it be possible to add an additional week if it's not too much trouble?

If any problems or questions or if I can be of any help, please feel free to let me know,

Best,
Lucie

**Pull request merged**
