### PR TITLE
First commit for USC-SIkJalpha scenario forecasts

### PR DESCRIPTION
**Pull request by scc-usc**
## Description

Adding the first submission of USC-SIkJalpha scenario modeling forecasts.   

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: USC
- Model Name: SIkJalpha
- Institution:  University of Southern California
---

## Checklist

- [x] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Running-Checks-Locally).

### CODE REVIEW

**Comment by scc-usc** [comment]
I realized that the scenarios needed to be generated with the date Jan 3rd. I have regenerated all the targets without using data after Jan 3rd.

**Comment by LucieContamin** [comment]
Hi @scc-usc, 
Thank you for your pull-request and for the update. 
As I understand, you regenated your data. In this case, should we use the second file that has been generated?  

Thanks, Lucie

**Comment by scc-usc** [comment]
Yes, the second file is the one, as dated, based on data until Jan3rd. I didn't delete the previous one, in case other dates were also acceptable or useful in the future. But if forecasts based on other than Jan 3rd data are not acceptable, please feel free to remove "2021-01-06 ... .csv"

Thanks,
Ajitesh

**Comment by scc-usc** [comment]
The following changes have been made to my file:

- target_end_date: This was previously mislabeled based on the generation date of today, labeling 1 wk ahead as Jan 16th. Fixed it to start from Jan 9th.
- NaN values: Some NaN values were causing all national level values to be NaN. I have fixed the issue.

Thanks

**Comment by LucieContamin** [comment]
Hi @scc-usc,

Thank you for the updates. 

Just for information, the metadata file format is different than the one from the Forecast Hub. You can find information here: https://github.com/midas-network/covid19-scenario-modeling-hub/blob/master/data-processed/METADATA.md. We will accept a file without the fields that have "Not applicable" as possible values. By default, we will confider all these missing fields with the value "Not applicable". 

The metadata file you provide is in a good format, it's just missing these fields. So, it was to inform you that we will consider these fields with the value: "Not applicable". 

Please feel free to let me know if you have any questions.

Thanks, Lucie

**Comment by scc-usc** [comment]
Hi Lucie,

I apologize for the oversight. I have modified the metadata to add the missing information

Thanks,
Ajitesh

**Comment by LucieContamin** [comment]
Hi Aijitesh,

Thank you for the modification.
Thanks, Lucie

**Pull request merged**
