### PR TITLE
UNCC Round 17 submission

### PR DESCRIPTION
**Pull request by lunarmouse**
## Description

Please include a brief description of your change.  

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: 
- Model Name: 
- Institution:  
---

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new scenarios** to an existing model, please include the following details:- 
- Team name: UNCC
- Model name that is being updated:  Hierbin
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Scenario-File-Checks).

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @lunarmouse ,

It seems that the validation has some issues. The output message is incomplete here so I will take a look and work on it. I apologize for the inconvenience.
 In the meantime, I noticed some issues that might cause a problem here:
 - the name of the files should match your team-model name (as in the metadata and folder name), so it should be:
      - data-processed/UNCC-hierbin/metadata-UNCC-hierbin.txt
      - data-processed/UNCC-hierbin/2023-04-16-UNCC-hierbin.gz.parquet 
      - data-processed/UNCC-hierbin/2023-04-16-UNCC-hierbin-Abstract.md

Would it be possible to fix it, please?

- Also, it seems that one of the column name is incorrectly written, and so the validation cannot run:
```
❌ Error 103: At least one column name is misspelled or does not correspond to the expected column names. The column(s) `type.id` do(es) not correspond to the standard. The rest of the validation checks cannot be done if the columns names are not in the expected standard format
```
The column should be "type_id".

Please let me know if any questions or issues,
Thanks,

Lucie

**Comment by lunarmouse** [comment]
Hi Lucie I have updated the file. The error message seems irrelevant to the submission ( Failed to get R release: Failed to get R [object Object]: Failed to install R: Error: The process '/usr/bin/sudo' failed with exit code 100). Please let me know if there is anything that I need to revise on my side. Thanks, SC

**Comment by LucieContamin** [comment]
Hi, 
It seems to be a GitHub Actions related issue, I restarted it. 
Thanks, Lucie

**Comment by lunarmouse** [comment]
Hi Lucie I am not sure what the error message "Error 510: Each group combination should have one unique value. 74880 unique groups have been identified with this issue. " means, I checked how the data frame was set up and it seemed to be fine to me. I guess because there were a lot of 0s in this round (i.e., a lot of zero death in the projection), it might lead the validation algorithm to think they were redundant and triggered an error message. Could you please help verify this? Thanks, SC

**Comment by LucieContamin** [comment]
Hi again!

The error 510 and 902 are redundant with each other. They test the same issue in different way in case only one way trigger an error, but sometimes the 2 messages are triggered. 
It means that for each type_id (sample) should be associated with an unique scenario-location-target-horizon group, please find here more information: https://github.com/midas-network/covid19-scenario-modeling-hub/tree/master/data-processed#sample

For example, the submission can have 100 individual trajectories for the US/Scenario A/inc hosp/horizon 1 marked as 1 to 100 in the column "type_id". Then 100 individual trajectories for the US/Scenario A/inc hosp/horizon 2 marked as 1 to 100 in the column "type_id", etc. 

Please let me know if any other questions or issues,
Best,
Lucie

**Comment by lunarmouse** [comment]
Thanks Lucie! Looks like I have got some end-of-semester headache so the data frame variable names got messed up 🔢

**Comment by LucieContamin** [comment]
Hi @lunarmouse,

I noticed after merging that there is some issues with the abstract. Would it be possible to open a PR with an update the abstract for the round 17, please?
The file should be named: "2023-04-16-UNCC-hierbin-Abstract.md" and the content of the abstract should match the 2023-04-16-MyTeam-MyModel-Abstract.md  (https://github.com/midas-network/covid19-scenario-modeling-hub/blob/master/data-processed/MyTeam-MyModel/2023-04-16-MyTeam-MyModel-Abstract.md )

Please let me know if any issues or questions,
Thanks,
Lucie

**Pull request merged**
