### PR TITLE
Round 18 projections

### PR DESCRIPTION
**Pull request by mooresea**
## Description

Please include a brief description of your change.  

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: 
- Model Name: 
- Institution:  
---

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new scenarios** to an existing model, please include the following details:- 
- Team name: 
- Model name that is being updated:  
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Scenario-File-Checks).

### CODE REVIEW

**Comment by mooresea** [comment]
I didn't realize that age groups were required this round. Adding these would require rerunning all of our projections, so will probably take a couple of extra weeks.

**Comment by LucieContamin** [comment]
Hi @mooresea,

Thanks for the submission. The three age groups are required indeed, so the validation will return an error if they are missing. However, I can ignore that error and we will accept a submission with only the overall population.

Also, just to be sure I understand correctly the "grouping" information in the submission: each model runs has different `run_grouping` (model run independent) for every `stochastic_run`, grouped by `age group`, `horizon`, `location`, `scenario_id`, `target`,  like the example 2 in the Sample documentation page (https://scenariomodelinghub.org/documentation/sample_format.html) but with additional grouping. Is that correct?

Please feel free to let me know if any issues or questions,
Best, Lucie

**Comment by mooresea** [comment]
Lucie,

My projections are grouped by horizon, age group, location, and scenario_id
which I think is closest to example 5 in the sample documentation. And
there is only one stochastic run for each sample.

Thanks,
Sean

**Comment by LucieContamin** [comment]
Hi again,

Thanks for the quick reply. Just to verify for the "grouped" by information in the submission, I have the `target` included, meaning the projection are grouped by `age group`, `horizon`, `location`, `scenario_id`, `target` . Is that correct? 
For example, in the submission file: the trajectory with  run_grouping `1` and the stochastic_run `1` contains all the age groups, horizons, locations, scenarios and targets. 
If the projections are not grouped by target, shouldn't we have the 2 targets in different trajectory ID? does that make sense? 

Please feel free to let me know if any issues or questions,
Best, Lucie

**Comment by mooresea** [comment]
Lucie, yes the trajectories are also grouped by target.

**Comment by LucieContamin** [comment]
Thank you for the confirmation, 
Best, Lucie

**Pull request merged**
