### PR TITLE
Adding round 11 results for UF-ABM

### PR DESCRIPTION
**Pull request by tjhladish**
## Description

Initial submission of round 11 results for UF-ABM

- Team name: UF
- Model Name: ABM
- Institution: University of Florida

### CODE REVIEW

**Comment by harryhoch** [comment]
do you have a metadata file?

**Comment by tjhladish** [comment]
We have the ~500 word abstract, but we only learned about the metadata file
while figuring out how to submit results last night.  Neither of us who
attended the round 11 meetings recall it being mentioned.  Are both the
abstract and the metadata file needed?

Tom

**Comment by harryhoch** [comment]
yes, we do need metadata in the specified file format.

Also, just confirming - is all of your data from Florida?

**Comment by tjhladish** [comment]
All of our model output represents predictions for the state of Florida.

We're working on the metadata today.

**Comment by harryhoch** [comment]
great. thanks

**Comment by tjhladish** [comment]
I've added a commit with the metadata file

**Comment by harryhoch** [comment]
@tjhladish , your data contained only quantiles and no point estimates. This causes problems for our code. Can you update with point estimates?

**Comment by tjhladish** [comment]
What do you mean by point estimates?  The results include medians.

**Comment by csmith701** [comment]
Hi @tjhladish - the format of the submission includes both quantiles and point estimates. The point estimate is denoted in the submission file by setting `type` = "point" and `quantile` = NA. You can find all the detail here:

https://github.com/midas-network/covid19-scenario-modeling-hub/blob/master/data-processed/README.md

It's fine to use your medians as your point estimates (most teams do that), but we ask that you have the point estimate included separately in the submission so formatting is aligned across teams and our code can properly process/plot your results.

**Comment by tjhladish** [comment]
Okay.  I won't be able to modify the format before today's meeting, but
should be able to do it later today.

**Comment by harryhoch** [comment]
Thanks, @tjhladish

**Comment by harryhoch** [comment]
looks good. will be up on staging soon.

**Comment by tjhladish** [comment]
Thank you

**Pull request merged**
