### PR TITLE
Update 2022-06-05-UNCC-Abstract.md

### PR DESCRIPTION
**Pull request by lunarmouse**
## Description

Please include a brief description of your change.  

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: 
- Model Name: 
- Institution:  
---

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new scenarios** to an existing model, please include the following details:- 
- Team name: 
- Model name that is being updated:  
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Scenario-File-Checks).

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @lunarmouse,

Thank you very much for updating the abstract. However, some sections of the abstract also change between round 13 and round 14. Would it be possible to update it, please? For example the `## Initial variant characteristics` section has been updated to `## Initial variant characteristics (including Omicron transmissibility, immune escape, whether BA4/BA5 were considered and how uncertainty or non-identifiability was handled) `. 

Please feel free to let me know if any questions,

Best, 
Lucie

**Comment by lunarmouse** [comment]
Hi Lucie, sure I can update the abstract. Could you please let me know where the updated template is located? I seem not be able to find it on GitHub, so I recycled the round 13 one.

**Comment by LucieContamin** [comment]
Thanks for the quick reply, 
The Round 14 template, is available [here](https://github.com/midas-network/covid19-scenario-modeling-hub/blob/master/data-processed/MyTeam-MyModel/2022-06-05-MyTeam-MyModel-Abstract.md): https://github.com/midas-network/covid19-scenario-modeling-hub/blob/master/data-processed/MyTeam-MyModel/2022-06-05-MyTeam-MyModel-Abstract.md

Best,
Lucie

**Comment by lunarmouse** [comment]
Thanks Lucie, I have updated the abstract -- saw it went through! 
Have a good one,
Shi

**Pull request merged**
