### PR TITLE
UTA-ImmunoSEIRS - R14 projections

### PR DESCRIPTION
**Pull request by MPS7**
## Description

The projection file was compressed and then splitted due to its large size (387mb). In order to obtain the compressed ".gz" file (118mb), please first run the following Linux/Unix command:
$ cat 2022-05-31-UTA-ImmunoSEIRS.csv.bz.* >2022-05-31-UTA-ImmunoSEIRS.csv.gz

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @MPS7 ,

Thanks for your submissions, I have some questions about it. 

First, I wanted to warn you that I am currently updating the automatic validation for Round 14 but it's not ready yet so I will double check manually until the validation is up to date. The validation should be running for June, 7 if you prefer to wait. 

I look at the files you submit and I was surprise about the size if it. It seems that when I open it, I obtain a CSV file with some unexpected value in the column `value`. For example, for the first week ahead cum death, scenario A, location 01, quantile 0.5, the value column contains 52 different values instead of 1. Would it be possible to verify that all rows contains only 1 value? That might also explain the problem with the size of the file. 
Also, it seems that the date in the name of the file and the model_projection_date should be "2022-06-05", would it be possible to update, please?

Please feel free to let me know if you have any questions or troubles,

Best,

Lucie

**Comment by MPS7** [comment]
Hi Lucie,

Thank you for the suggestions and sorry for still making these silly mistakes. There was a problem with the code which generated arrays in the cumulative deaths values. I have corrected it and also fixed the model_projection_date value. The size of the new file is only about 22.5mb when compressed.

Best regards,
Anass

**Comment by LucieContamin** [comment]
Good morning,

I apologize for the delay. The validation code and associated package has been updated for Round 14. I still have some update to run so the automatic validation is not yet fully updated. However, I was able to run the validation on your submission locally (you can find information on local run for validation [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Scenario-File-Checks#file-checks-running-locally)), so please find below the results.

Please feel free to let me know if any issues or questions,

Best,
Lucie




"Run validation on file: 2022-06-05-UTA-ImmunoSEIRS.csv.gz" 

## Columns: 

No errors or warnings found on the column names and numbers 

## Scenarios: 

 No errors or warnings found on scenario name and scenario id columns
 
  ## Model Projection Date Column:  
  
  No errors or warnings found on the column 'model_projection_date' 
  
  ## Quantiles:
  
  No errors or warnings found on quantiles values and format 
  
  ## Value and Type Columns: 
  
  ❌ Error 508: Some values are less than the last oberved cumulative cases count. Please check location(s): c("02", "08", "09", "13", "15", "16", "17", "23", "24", "25", "32", "33", "34", "36", "41", "44", "50", "51", "53")
  ❌ Error 509: Some values are less than the last oberved cumulative deaths count. Please check location(s): c("01", "02", "04", "05", "06", "10", "12", "13", "15", "19", "20", "21", "23", "29", "30", "31", "32", "33", "35", "37", "39", "40", "41", "45", "47", "49", "50", "51", "53", "55", "56", "54") 
  
  ## Target Columns: 
  
   ❌ Error 601: At least one of the target_names is misspelled. Please verify, the target_names should be (optional target(s) inluded): 'inc death, inc case, cum death, cum case, inc hosp, cum hosp, inc inf, prop X'. The data frame contains: 'inc death, cum death, inc case, cum case, inc hosp, cum hosp, prop_X', as targets names. 
   
   ## Locations: 
   
   No errors or warnings found on Location

**Comment by MPS7** [comment]
Good morning Lucie,

Thank you very much for the response and for running the validation checks.
It seems that there is a mistake in the calculation of the baseline
cumulative cases and deaths. That's because I submitted the results before
the deadline and didn't account for the cases and deaths of the ongoing
week. I will submit the updated version on Monday to have accurate baseline
numbers.

Regarding the second mistake, there is an error in the name of the column
corresponding to the proportion of infections with variant X. I will
correct it in the next submission.

Best regards,
Anass

Le ven. 3 juin 2022 à 10:08, Lucie Contamin ***@***.***> a
écrit :

**Comment by LucieContamin** [comment]
Hi Anass,

Thank you very much for the quick reply. 
I will also let you know when the automatic validation is ready. 

Best,
Lucie

**Comment by MPS7** [comment]
Hi Lucie,

I have committed the projections with the corrected cumulative numbers and variant X proportion label. Also, I have committed the abstract for round 14.

Thank you for your assistance with this.

Best regards,
Anass

**Comment by LucieContamin** [comment]
Hi Anass,

Thank you very much for the update. It seems that the automatic validation still has some trouble, I will fix it quickly. I will run the validation manually again and send the results tomorrow. 

I apologize for  the inconvenience, please feel free to let me know if any questions or troubles. 

Best,
Lucie

**Comment by LucieContamin** [comment]
Good morning Anass,

Please find here the results of the manual validation, please feel free to let me know if any questions or troubles. Also, just for information, the visualization code is working, and the output is available in the artifacts of the associated validation GitHub actions if wanted.

Best,
Lucie

[1] "Run validation on file: 2022-06-05-UTA-ImmunoSEIRS.csv.gz"

 ## Columns: 

 No errors or warnings found on the column names and numbers 

## Scenarios: 

 No errors or warnings found on scenario name and scenario id columns 

 ## Model Projection Date Column:  

 No errors or warnings found on the column 'model_projection_date' 

## Quantiles: 

 No errors or warnings found on quantiles values and format 

## Value and Type Columns: 

 ❌ Error 509: Some values are less than the last observed cumulative deaths count. Please check location(s): 40 

## Target Columns: 

 No errors or warnings found in target and target_end_date columns 

## Locations: 

 No errors or warnings found on Location

**Comment by MPS7** [comment]
Hi Lucie,

I have updated the projections with corrected cumulative deaths and cases. I will check the automatic validation once it's done to see if everything goes well.

Best regards,
Anass

**Comment by LucieContamin** [comment]
Hi Anass,

Thank you for the update, it seems to be all good! I will merge the pull-request.

Best,
Lucie

**Pull request merged**
