### PR TITLE
Fixed horizon and type id column name mismatch

### PR DESCRIPTION
**Pull request by lunarmouse**
## Description

Please include a brief description of your change.  

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: 
- Model Name: 
- Institution:  
---

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new scenarios** to an existing model, please include the following details:- 
- Team name: uncc
- Model name that is being updated:  hierbin
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Scenario-File-Checks).

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @lunarmouse,

Thank you for the update, the submission file looks to all good.
I noticed after merging your last PR that there is some issues with the abstract. Would it be possible to update the abstract for the round 17 in this PR, please?
The file should be named: "2023-04-16-UNCC-hierbin-Abstract.md" and the content of the abstract should match the 2023-04-16-MyTeam-MyModel-Abstract.md (https://github.com/midas-network/covid19-scenario-modeling-hub/blob/master/data-processed/MyTeam-MyModel/2023-04-16-MyTeam-MyModel-Abstract.md )

Please let me know if any issues or questions,
Thanks,
Lucie

**Comment by lunarmouse** [comment]
Hi Lucie, thanks for the heads up. I updated the abstract based the current template. Have a nice day! Shi

**Comment by LucieContamin** [comment]
Hi Shi,

Thank you for the update! 
However, just a minor fix, would it be possible to remove the subsections in:
`Initial distribution of susceptibility (if available)`, please? (meaning removing the "Proportion of people that were infected with Omicron", "Proportion of people that are naïve at start of projection (not vaccinated or infected)" and "other" subtitle, it should only be free text).

Also, the filename seems to still miss the model name, could you please update it to "2023-04-16-UNCC-hierbin-Abstract.md"?

Many thanks,
Lucie

**Comment by lunarmouse** [comment]
Hi Lucie, I just fixed these issues and submitted a PR. Thanks! SC

**Comment by LucieContamin** [comment]
Thank you very much, it looks all good. I will merge the PR.
Best, Lucie

**Pull request merged**
