### PR TITLE
CU Round 13

### PR DESCRIPTION
**Pull request by tkcy**
## Description

Please include a brief description of your change.  

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: 
- Model Name: 
- Institution:  
---

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new scenarios** to an existing model, please include the following details:- 
- Team name: 
- Model name that is being updated:  
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Scenario-File-Checks).

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @tkcy ,

Thank you for your submission. It seems that the automatic validation has not run probably, I will update it to fix this problem. 

However, it seems that the validation script has trouble identifying the information in the file to run the validation. Both the scenario information and the name of file are necessary to run it.
 
Since Round 12, we update the `model_projection_date` and Name of the file definition to have a standard between all teams, to avoid any technical problem. So the "model_projection_date" value and the name of the file should be the same, and should correspond to the start date for scenarios (first date of simulated transmission/outcomes). So, for example, for Round 13, it should be `2022-03-13`. You can also find more information [here](https://github.com/midas-network/covid19-scenario-modeling-hub#model-projection-dates).
Would it be possible to update the `model_projection_date` column and filename to "2022-03-13", if necessary, please?

It also seems that the `scenario_id` column does not correspond to the expected value as in the [README](https://github.com/midas-network/covid19-scenario-modeling-hub). For example, scenario A should have for `scenario_id` value `A-2022-02-25`.
Would it be possible to update it, please?

By updating these 2 issues, it should solve the validation problem and it should run again correctly. 

I apologize for the inconvenience, please feel free to let me know if you have any questions or troubles.

Many thanks,

Lucie

**Comment by LucieContamin** [comment]
Hi @tkcy ,

It seems that the validation script runs and print a report this time. 
Just to add more information, the error message: ` Error: 'model_projection_date' is not corresponding to the name in the file, the date should correspond to: '2022-02-25'.` is confusing. The `model_projection_date` and filename date should be identical, by default the error message take the date in the filename even if the date is not the expected one. I apologize for the inconvenience and will work on it for the next round. 

Just to clarify:
- the 'model_projection_date' should contains the unique value `"2022-03-13" `
- the submission file should be named "2022-03-13-CU-AGE-ST.csv.zip". 
It should solved the issues

For the others issues, please feel free to let me know if you have any questions or troubles.

Many thanks,

Lucie

**Comment by tkcy** [comment]
Hi Lucie, Sorry I'm still confused.  Where does the 2022-02-25 go? Are all the dates supposed to be 2022-03-13?

**Comment by LucieContamin** [comment]
I understand my error message is very confusing, I will update it for next round. 
The "2022-02-25" should not be present in the file in the "model_projection_date" or in the filename (exception of the scenario_id: A-2022-02-25, B-2022-02-25, C-2022-02-25, D-2022-02-25). 
You are correct, all the dates in the "model_projection_date" and in the filename should be 2022-03-13.

**Comment by LucieContamin** [comment]
Just to add more information, on your current submission, the `scenario_id` column and the `model_projection_date` column are correct. It is just necessary to update the name of the submission file to "2022-03-13-CU-AGE-ST.csv.zip".

I apologize again for the confusion,

Please feel free to let me know if you need more information or have any questions, troubles.

Best,

Lucie

**Comment by tkcy** [comment]
Thanks Lucie, Hopefully it works this time!

**Comment by LucieContamin** [comment]
Good morning @tkcy ,

It seems to be all good now, thank you for the updates. Could you please let me know if the last Warning message is expected and if you would like me to merge the PR as it is or if you prefer to keep it open, to update some change later?

Please let me know if you have any questions or troubles,

Many thanks,

Lucie

**Comment by tkcy** [comment]
Hooray!  Yes the warning is expected, we don't output cumulative hospitalizations.  The file should be good to go. Thanks @LucieContamin !

**Comment by LucieContamin** [comment]
Thank you very much! I will merge the PR.

**Pull request merged**
