### PR TITLE
Round 18 submission for USC-SIkJalpha

### PR DESCRIPTION
**Pull request by scc-usc**
## Description

Round 18 submission

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: 
- Model Name: 
- Institution:  
---

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new scenarios** to an existing model, please include the following details:- 
- Team name: 
- Model name that is being updated:  
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Scenario-File-Checks).

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @scc-usc ,

Thanks for your submission! Just to add more information from the automatic message, the validation was not run because the submission file was not recognized, it needs to be named: `"2024-04-28-USC-SIkJalpha"`. 

Please let me know if any issues or questions,
Best, Lucie

**Comment by LucieContamin** [comment]
Hi @scc-usc ,

Thank you for your submission, I just wanted to verify that I understand correctly the sample ID numbering:  there is no stochasticity, every models runs has a different run_grouping "grouped" by age_group, location, horizon, scenario_id, and, target. Is that correct?

Please let me know if any issues or questions,
Best, Lucie

**Comment by scc-usc** [comment]
Each trajectory is generated by a predetermined set of hyperparameters. Once these hyperparameters are fixed, the trajectory is unique. "run_grouping" is the trajectory ID.

**Comment by LucieContamin** [comment]
Hi @scc-usc , thank you for the answer and additional answer!

Best, Lucie

**Comment by LucieContamin** [comment]
Hi again, 

I apologize for the multiple message, but I notice some small issues in your submission. It's ok for this round, but would it be possible for the next updates, submissions to provide the `horizon`, `run_grouping`, `stochastic_run` and `value` column in a numeric format, please? Please find [here](https://github.com/midas-network/covid19-scenario-modeling-hub/tree/master/data-processed#column-format), some documentation on the expected format of the submission.

Please let me know if any issues or questions,
Best, Lucie

**Pull request merged**
