### PR TITLE
UNCC Hierbin Round 13 Abstract

### PR DESCRIPTION
**Pull request by lunarmouse**
## Description

Please include a brief description of your change.  

---
> _If this section does not apply to you, please delete it in your PR_  

If this is a **new team submission**, please include the following details :-  
- Team name: 
- Model Name: 
- Institution:  
---

> _If this section does not apply to you, please delete it in your PR_  

If you are **adding new scenarios** to an existing model, please include the following details:- 
- Team name: 
- Model name that is being updated:  
---

## Checklist

- [ ] Specify a proper PR title with your team name.
- [ ] All validation checks ran successfully on your branch. Instructions to run the tests locally is present [here](https://github.com/midas-network/covid19-scenario-modeling-hub/wiki/Scenario-File-Checks).

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @lunarmouse ,

Thank you for submitting the abstract. However, the format of the abstract for Round 13 has changed a little bit. Would it be possible to follow the format as in the example: [2022-03-13-MyTeam-MyModal-Abstract.md](https://github.com/midas-network/covid19-scenario-modeling-hub/blob/master/data-processed/MyTeam-MyModel/2022-03-13-MyTeam-MyModal-Abstract.md).

Please feel free to let me know if any questions or troubles,

Thanks,
Lucie

**Comment by lunarmouse** [comment]
Thanks Lucie, I have updated the abstract based on the new abstract template you provided.

Best, 
Shi

**Comment by LucieContamin** [comment]
Thanks for the quick update!
I just have a quick question, it seems that in your last version of the abstract you still have some "old" sections, for example from line 35 to line 43:
```
## Initial distribution of susceptibility
Initial distribution of susceptibility is set as all individuals in the state except recently infected or recovered. Boosted individuals will have a certain probability to be infected again by the Omicron variant (i.e., being susceptible).
## Transmissibility
Transmissibility is modeled as an interaction between both immune escape specifications and waning mmunity. 
## Generation time
Generation time is implicitly modeled due to the data-driven nature of our model.
## Waning immunity assumptions
Waning immunity is modeled as in round #13 specification. Stochastic noise is introduced to waning immunity in each run.
```
Would it be possible to integrate it to other sections, please? We would prefer to have all the abstracts for round 13 with the same sections, to facilitate processing. 

Also just for information, it seems that your abstract starts with multiple lines, it's not a problem, but just to inform you they might get removed during the processing. 

Many thanks,

Lucie

**Comment by lunarmouse** [comment]
Hi Lucie, thanks for the reminder, looks like I messed up the two versions. So this version should have all updated information. Best, Shi

**Comment by LucieContamin** [comment]
Thank you very much for the update! It looks all good now, I will merge the PR. 

Best,
Lucie

**Pull request merged**
